// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByyxA0Xcnakz-FA5SZNXXEVUNKd6ZbCvE',
    appId: '1:907624467282:web:1f435aecc12d267edbc88b',
    messagingSenderId: '907624467282',
    projectId: 'uplace-1-0',
    authDomain: 'uplace-1-0.firebaseapp.com',
    storageBucket: 'uplace-1-0.appspot.com',
    measurementId: 'G-54PEN4DCP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBifOUL7P6JhW_qeRCS_WSMj9AEWH3864s',
    appId: '1:907624467282:android:f6ada18378efafacdbc88b',
    messagingSenderId: '907624467282',
    projectId: 'uplace-1-0',
    storageBucket: 'uplace-1-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa73x732g_UQnVW5cEkJ-b7nfPd3H5MjA',
    appId: '1:907624467282:ios:d5e307ac985eae4bdbc88b',
    messagingSenderId: '907624467282',
    projectId: 'uplace-1-0',
    storageBucket: 'uplace-1-0.appspot.com',
    iosBundleId: 'com.example.uplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa73x732g_UQnVW5cEkJ-b7nfPd3H5MjA',
    appId: '1:907624467282:ios:a8494c069088b93cdbc88b',
    messagingSenderId: '907624467282',
    projectId: 'uplace-1-0',
    storageBucket: 'uplace-1-0.appspot.com',
    iosBundleId: 'com.example.uplace.RunnerTests',
  );
}
